### ISSUE TITLE
Add prepublish script to package.json

### ISSUE THREAD

**Issue by pwnall** [Autarc/optimal-select#13]
I think you need to run `npm run build` to obtain the module published on npm from this repository. If I'm correct, please consider adding a `prepublish` key to your `scripts` in `package.json`.

```javascript
    "prepublish": "NODE_ENV=production node build"
```

**Comment by Autarc** [comment]
The distributed version on npm should be ready to use. In addition to the transpiled source files in `lib`, it includes a pre-bundled version for the browser as well in the `dist` directory. Since I update the latest version with each new built it shouldn't be necessary to call it yourself. Nevertheless for convenience a `prepublish` script got added to ensure it remains this way.

**Comment by pwnall** [comment]
Thank you!
