### ISSUE TITLE
DOMException: Failed to execute querySelectorAll

### ISSUE THREAD

**Issue by venkatkarun** [Autarc/optimal-select#2]
While running on http://www.csszengarden.com/, optimal-select threw DOMException: Failed to execute 'querySelectorAll' on 'Document': '#zen-explanation >p:nth-child(2) Style Sheets"]:nth-child(1)' is not a valid selector. You can see results with css-selector-generator and a homebrewn one below. 

optimal-select: null
css-selector-generator: #zen-explanation > :nth-child(2) > :nth-child(1) 
homebrewed: #zen-explanation > p:nth-of-type(1) > abbr:nth-of-type(1)

**Comment by Autarc** [comment]
Thanks for mentioning it. The problem was caused by splitting the selector segments at the optimization phase. With the change in ff195f5d68fc1958bc33a2bcd99191cae0ebdcc7 attribute values with spaces are handled properly.

For the provided example the generated selector is a bit longer but less specific and therefore more robust towards DOM modifications.

optimal-select: `#zen-explanation p:nth-child(2) [title="Cascading Style Sheets"]:nth-of-type(1)`

**Comment by venkatkarun** [comment]
Thanks for the super quick fix. The library is robust and fast. Great work!
