### ISSUE TITLE
Array.from is not supported by many browsers

### ISSUE THREAD

**Issue by xMartin** [Autarc/optimal-select#21]
The distribution version uses `Array.from` which is not part of ES5 and doesn't have general browser support. Either replace it or add a polyfill.

**Comment by Autarc** [comment]
Well I guess it depends on how we define *general browser support*. Since modern browsers are the main targeted environments the [feature compatibility of the library](http://kangax.github.io/compat-table/es6/#test-Array_static_methods_Array.from,_array-like_objects) is actually covering most cases.

Nevertheless I understand its still going to be an issue and therefore replaced the inflicting lines with alternatives. Without the implicit conversion through the spread syntax and destructuring, the static `Array.from` method won't be used by the transpiler.

**Comment by xMartin** [comment]
Thanks. I was assuming you're transpiling to ES5 which Array.from is not, as I understand it.

**Comment by xMartin** [comment]
It works for me now.
